---
- name: install > Packages
  package:
    name: apparmor
    state: present
  become: yes

- name: configs > Ensures destination directories exists
  file:
    path: /etc/apparmor.d
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: configs > Create files
  copy:
    content: "{{ item.profile }}"
    dest: "/etc/apparmor.d/{{ item.filename }}"
    owner: root
    group: root
    mode: "0644"
  when: item.state|default('present') != 'absent'
  with_items: "{{ config.apparmor }}"
  become: yes
  notify:
    - apparmor reload

- name: configs > Remove files
  file:
    path: "/etc/apparmor.d/{{ item.filename }}"
    state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ config.apparmor }}"
  become: yes
  notify:
    - apparmor reload
