---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airship-host-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airship-host-config
  template:
    metadata:
      labels:
        name: airship-host-config
    spec:
      serviceAccountName: airship-host-config
      containers:
        - name: airship-host-config
          # Replace this with the built image name
          image: "quay.io/sirishagopigiri/airship-host-config"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - mountPath: /opt/ansible/data
            name: data
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "airship-host-config"
            - name: ANSIBLE_FILTER_PLUGINS
              value: /opt/ansible/plugins/filter
            - name: ANSIBLE_FORKS
              value: "100"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_INVENTORY
              value: /opt/ansible/inventory
            - name: USER
              value: "USERNAME"
            - name: PASS
              value: "PASSWORD"
            - name: SECRET_NAMESPACE
              value: "default"
      volumes:
        - name: runner
          emptyDir: {}
        - name: data
          emptyDir: {}
